const translations = {
    en: {
        // Navigation
        home: "Home",
        about: "About",
        projects: "Projects",
        contact: "Contact",
        portfolio_learning: "Learning Portfolio",
        project_context: "Context",
        project_progress: "Project Progress",
        technical_challenges: "Technical Challenges",
        skills_acquired: "Skills Acquired",
        conclusion: "Conclusion",

        // Project specific
        project_title: "MyAvatar - Universal Avatar Management Service",
        context_text_p1: "As part of the R5.A.05 - Advanced Web Programming course, I developed MyAvatar, a web application inspired by Gravatar allowing users to associate a profile picture with their email addresses, universally accessible via a unique URL generated by SHA256 hashing.",
        context_text_p2: "Developed in a team of four developers with Symfony, this project deepened web security skills (authentication, secure file management), real-time AJAX validation, and REST API design. My role focused on the avatar CRUD system and permissions management.",

        phase_1_title: "Main Features",
        progress_list_1: "Secure authentication with Symfony Security and bcrypt hashing",
        progress_list_2: "Real-time AJAX validation to check identifier availability",
        progress_list_3: "Complete CRUD system for avatar management (upload, modification, deletion)",
        progress_list_4: "Secure file storage outside web directory with access controlled by BinaryFileResponse",
        progress_list_5: "Automatic SHA256 hash generation for each email (public route /avatar/{hash})",
        progress_list_6: "Secondary email support with multiple hashes",
        progress_list_7: "Profile visibility management with permission system (users/admins)",
        progress_list_8: "Administration interface and maintenance mode",

        challenges_list: [
            "Securing storage and serving files via BinaryFileResponse with permission control",
            "Managing multiple SHA256 hashes with automatic recalculation on modifications",
            "REST API with AJAX validation and debouncing for performance optimization",
            "3-level permission architecture (anonymous, authenticated, admin) via Symfony voters"
        ],

        skills_list: [
            "Symfony mastery (Security, Forms, Doctrine ORM, Twig)",
            "Web security: secure file management, SHA256/bcrypt hashing, OWASP prevention",
            "REST API development with asynchronous validation",
            "Relational database architecture with Doctrine",
            "Collaborative work with Git and Docker deployment"
        ],

        conclusion_text: "MyAvatar allowed me to develop solid skills in Symfony and web security, while experiencing collaborative teamwork. The project, deployed in production and publicly accessible, demonstrates my ability to design and deliver a complete and secure web application, from conception to online deployment.",

        see_on_github: "View on GitHub",
        link_to_project: "Link to the project",
        previous_project: "← Previous Project",
        next_project: "Next Project →"
    },
    fr: {
        // Navigation
        home: "Accueil",
        about: "À propos",
        projects: "Projets",
        contact: "Contact",
        portfolio_learning: "Portfolio d'apprentissage",
        project_context: "Contexte",
        project_progress: "Déroulement du projet",
        technical_challenges: "Défis techniques",
        skills_acquired: "Compétences acquises",
        conclusion: "Conclusion",

        // Project specific
        project_title: "MyAvatar - Service de Gestion d'Avatars Universels",
        context_text_p1: "Dans le cadre de la ressource R5.A.05 - Programmation Avancée Web, j'ai développé MyAvatar, une application web inspirée de Gravatar permettant aux utilisateurs d'associer une image de profil à leurs adresses email, accessible universellement via une URL unique générée par hachage SHA256.",
        context_text_p2: "Réalisé en équipe de quatre développeurs avec Symfony, ce projet a permis d'approfondir la sécurité web (authentification, gestion sécurisée des fichiers), la validation AJAX en temps réel, et la conception d'API REST. Mon rôle s'est concentré sur le système CRUD des avatars et la gestion des permissions.",

        phase_1_title: "Fonctionnalités Principales",
        progress_list_1: "Authentification sécurisée avec Symfony Security et hachage bcrypt",
        progress_list_2: "Validation AJAX en temps réel pour vérifier la disponibilité des identifiants",
        progress_list_3: "Système CRUD complet pour la gestion des avatars (upload, modification, suppression)",
        progress_list_4: "Stockage sécurisé des fichiers hors répertoire web avec accès contrôlé par BinaryFileResponse",
        progress_list_5: "Génération automatique de hachages SHA256 pour chaque email (route publique /avatar/{hash})",
        progress_list_6: "Support des emails secondaires avec hachages multiples",
        progress_list_7: "Gestion de la visibilité des profils avec système de permissions (utilisateurs/admins)",
        progress_list_8: "Interface d'administration et mode maintenance",

        challenges_list: [
            "Sécurisation du stockage et servir les fichiers via BinaryFileResponse avec contrôle des permissions",
            "Gestion des hachages SHA256 multiples avec recalculation automatique lors des modifications",
            "API REST avec validation AJAX et debouncing pour optimiser les performances",
            "Architecture de permissions à 3 niveaux (anonyme, authentifié, admin) via Symfony voters"
        ],

        skills_list: [
            "Maîtrise de Symfony (Security, Forms, Doctrine ORM, Twig)",
            "Sécurité web : gestion sécurisée des fichiers, hachage SHA256/bcrypt, prévention OWASP",
            "Développement d'API REST avec validation asynchrone",
            "Architecture de BDD relationnelle avec Doctrine",
            "Travail collaboratif avec Git et déploiement Docker"
        ],

        conclusion_text: "MyAvatar m'a permis de développer des compétences solides en Symfony et en sécurité web, tout en expérimentant le travail collaboratif en équipe. Le projet, déployé en production et accessible publiquement, démontre ma capacité à concevoir et livrer une application web complète et sécurisée, de la conception à la mise en ligne.",

        see_on_github: "Voir sur GitHub",
        link_to_project: "Lien vers le projet",
        previous_project: "← Projet Précédent",
        next_project: "Projet Suivant →"
    }
};

document.addEventListener('DOMContentLoaded', () => {
    const languageSelect = document.getElementById('languageSelect');

    function setLanguage(lang) {
        localStorage.setItem('selectedLanguage', lang);
        updateContent(lang);
    }

    function updateContent(lang) {
        document.querySelectorAll('[data-translate]').forEach(element => {
            const key = element.getAttribute('data-translate');

            // Gestion des listes
            if (element.tagName === 'UL') {
                const translationKey = translations[lang][key];
                if (Array.isArray(translationKey)) {
                    element.innerHTML = '';
                    translationKey.forEach(item => {
                        const li = document.createElement('li');
                        li.innerHTML = item;
                        li.className = 'challenge-list';
                        element.appendChild(li);
                    });
                }
            }
            // Gestion des éléments de liste individuels
            else if (element.tagName === 'LI') {
                const keys = key.split('.');
                let translation = translations[lang];
                for (const k of keys) {
                    translation = translation[k];
                }
                if (translation) {
                    element.innerHTML = translation;
                }
            }
            // Gestion du texte normal
            else {
                const translation = translations[lang][key];
                if (translation) {
                    element.textContent = translation;
                }
            }
        });
    }

    languageSelect.addEventListener('change', (e) => {
        setLanguage(e.target.value);
    });

    // Charge la langue sauvegardée ou par défaut
    const savedLanguage = localStorage.getItem('selectedLanguage') || 'fr';
    languageSelect.value = savedLanguage;
    updateContent(savedLanguage);
});
